#!/usr/bin/env ruby

require './_sh/logic'

pe = ProjectsExecuter.new
#pe.update_repos
pe.update_projects_lists

#### update top readme
my_projects  = FOLDERS.map{|x| "http://github.com/mindreframer/#{x}"}
